#!/bin/sh
#
# Dieses Shell-Script setzt für die AVI-files das
# Verzeichnis /video voraus - bei mir ein Link auf
# das tatsächliche Verzeichnis.
#
# This shell-sript assumes a directory /video for the AVI-files
# (This might be well a link to your actual directory.
# Because all other scripts assume also that
# "video" is in the absolute filename it might be
# a good idea to create such a directory.
# It might be even good to have a link from that directory
# to /video. :-))
#
direct=/video  # !!!!
#
# I also use the following name-convention:
# filesnames starting with captials are avi-files or
# encoded files.
# Editlists must not start with captials.
# Of course it's up to you to change this :-))
#
# Die Qualitätsangabe ist ein wenig obsolet:
# Eigentlich ist bei Wiedergabe über einen DVD-Player
# alles unter 75 wenig sinnvoll.
#
# mpeg 2 und SVCD verlangen 720x576 anders geht es noch nicht!
#
# Wegen des Shellscripts "codiere" verwende ich folgende Konvention:
# Dateinamen, die mit Grossbuchstaben beginnen, sind AVI-files.
# editlisten beginnen mit Kleinbuchstaben. Man kann das natürlich
# auch anders machen. :-))
#
echo -e "Dateiname (Bitte mit Grossbuchstaben anfangen) ?? \c"
#
# English: echo -e "Filename to record to (Please start with captial) ?? \c"
#
read titel
echo -e "Qualität 30 -100 ( Enter = 100 ) \c"
#
# English: echo -e "Quality 30 - 100 (ENTER = 100 ) \c"
#
read qual
if [ -z "$qual" ]
then
qual=100
fi
#
# Falls doch einmal von 768 runter gerechnet werden kann :-))
#
echo -e "SVCD = A    VCD = B  (Enter = SVCD) \c"
read format
if [ -z "$format" ] || [ "$format" = "a" ] || [ "$format" = "A" ]
then
format="-g 720x576 -d 1"
else
format="-d 2"
titel=${titel}_vcd
fi
echo -e "\n Dauer in Minuten? (Enter = 180 Min) \c"
#
# English: echo -e "\n Recording time in minutes (ENTER = 180 min) \c"
#
read minuten
if [ -z "$minuten" ]
then
minuten=180
fi
zeit=`expr $minuten \* 60`
echo " Aufnahmedauer für $titel: $zeit Sekunden "
#
# English: echo "Recording time for $titel: $zeit seconds "
#
echo -e "Wartezeit (Min) or ENTER um sofort anzufangen  \c"
#
# English: echo -e "Minutes to wait or ENTER to start recording \c"
#
read warte
if [ -z "$warte" ]
then
warte=0
else
warte=`expr $warte \* 60`
fi
sleep $warte
lavrec -f a -i p -c 2 -a 16 $format -s -r 44100 -l 90 -R l -q $qual -t $zeit $direct/${titel}%03d.avi
#
# c = Korrektur für audio und video Sync  t=sekunden
# f = format ( A und a sind Avi )
#

