#!/bin/sh
#
# codiere ist ein Shellscript das entweder AVI-files bearbeitet.
# Bei AVI-Files wird der Name des AVI-Files auch fr die komprimierten
# Files verwendet - erweitert um entsprechende Žnderungen.
# AVI-Files beginnen - so setzt es das script voraus - mit
# einem Grossbuchstaben und enden mit Kleinbuchstaben.
# Editlisten beginnen mit Kleinbuchstaben und es wird folgendes
# Schema verwendet: ja01[a - z] wird zum ersten File zusammengefasst.
# Die Dateien ja02[a-7] werden zum zweiten File zusammengefasst.
#
# Have a look at the README_aufnahme.....
# The dialogs are translated, but the explanations are all in the
# README - I'm lazy :-)))
#
direct=/video #!!!!!!!!!!!!!!!!!!!!11
#
cd $direct
echo -e "\n  Ist der erste Buchstabe gross, werden avi-Files bearbeitet."
echo "  Ist der erste Buchstabe klein,"
echo "  werden ohne weitere Prfung editlisten vorausgesetzt"
echo -e "\n\n Welche Dateien bearbeiten? \c"
# English:
# echo -e "\n If the first letter oft the filename is a capital letter
# echo "I'll asume avi-files."
# echo "  Otherwise editlists are assumed."
# echo -e "\n\n Which files should I process? \c"
read c
echo -e " Filterst„rke angeben (0 - 2) \c"
# English echo -e " Which filters should I use ( 0 - 2 ) \c"
read filter
if [ "$filter" = "0" ]
	then
	filter="-n 0"
        filter2=" "
	mpegfilter="-h"
	else
	filter="-n $filter"
        filter2="lav2dfilter"
#
# lav2dfilter" bringt nicht viel, kostet Zeit.
# „hnliches gilt fr die Erh”hung von GOPS
#
# I don't see much improvement from lav2dfilter - but here it is.
# Changing GOPS didn't result in an improvement - according to my eyes
#
	mpegfilter="-N"
#	mpegfilter="-N" bringt das so viel??
fi
echo -e "Bitrate 1152 - 2500 \c"
read brat
# Breitband-Video: Das sind die Filme, bei denen oben und unten
# ein schwarzer Rand zu sehen ist und bei manchen Fernsehern
# die Seiten ein wenig abgeschnitten werden. Also: Leinwandfilme,
# die im Fernsehen ausgestrahlt werden.
# Da empfiehlt es sich, diese fast schwarzen R„nder abzuschneiden.
# Das verbessert die Kompression weil nicht im Schwarz-Flimmern
# nach Ver„nderungen gesucht werden muss.
#
echo -e "B = Breitbandvideo     ENTER = normales Video \c"
# English
# echo -e "B = Wideformat-movie     Enter = normal video \c"
read breit
if [ "$breit" = "b" ] || [ "$breit" = "B" ]
then
BREIT=1
else
BREIT=0
fi
# Wurde die Aufnahme bereits als vcd gemacht und enth„lt die
# Hinweis darauf im Namen? Dann muss nicht viel gefragt werden,
# ausser nach der Bitrate. SVCD und XVCD k”nnen aus diesen
# Aufnahmen sowieso nicht mehr gemacht werden :-)
# Die Randbreiten wurden experimentell gewonnen, wenn jemand
# das genauer machen kann: Bitte verbessern!
#
# Auch bei "normalen" VHS bzw. Video - Aufnahmen wird oben und
# unten ein kleiner Rand abgeschnitten. Die obersten und untersten
# Zeilen enthalten meistens nur Geflimmer.
#
# If recorded as vcd (taken from extension):
# No further questions necessary, we assume optimal values
# Improvements are welcome.
#

VCD=`echo ${c}* | grep vcd`
if [ -n "$VCD" ] && [ ${c} \> "Zz" ]
	then
	#
	# Optimale Werte einstellen - Zeit spielt keine Rolle, ist
	# sowieso rasend schnell.
	#
	qopt="-4 1 -2 1"
	if [ $BREIT = "1" ]
	then
	lavopt="-s 1 $filter -a 352x202+0+43"
        else
	lavopt="-s 1 $filter -a 352x270+0+9"
	fi
	mpegopt="-m 1 -s -b $brat $quopt $mpegfilter -r 16 "
	mplexopt="vcdmplex"
#
# Nein, nicht mplex - bei mir erzeugte mplex eine etwas zu hohe
# Bitrate - der Film ruckelt auf dem DVD-Spieler. Bei vcdmplex
# habe ich dieses Ph„nomen nicht.
#
# No, don't use mplex, unless you are really sure, that it works
# for you - my DVD-Player fails - bitrate might be slightly too high
#
# mplex versuchte ich mit: mplex I tried:  mplexopt="mplex -f 1 -S 840"
#
	add="${brat}_vcd"
	o="VCD MPEG 1 : $brat "
else
# Ist keine VCD-Aufnahme - deshalb ist Abfrage sinnvoll
#
	echo -e "Felddiagnose a=optimal b=schnell ( 30% schneller, reicht meistens) \c"
# English: echo -e "a = optimised for quality b = optimised for speed in most cases a isok \c"
	read qopt
	if [ $qopt = "a" ] || [ "qopt" = "A" ]
		then
		quopt="-4 1 -2 1"
		else
		quopt=" "
		fi
		echo -e "\nA = SVCD    B = XVCD   C = VCD   ( ENTER = SVCD ) \c"
		read F
		if [ -z "$F" ]
			then
			F="a"
			fi
		if [ "$F" = "A" ] || [ "$F" = "a" ]
		then
		d=$brat
		f=2
		if [ "$BREIT" = "1" ]
		then
		lavopt="-s 2 $filter -a 480x406+0+90"
		else
		lavopt="-s 2 $filter -a 480x540+0+18"
		fi
		mpegopt=" -m 2 -q 4 -b $brat $quopt $mpegfilter -r 16 -F 0"
		mplexopt=" mplex -m 2 -f 3 -V -S 840"
		o="SVCD MPEG 2 mit $brat "
		add="${brat}_m2"
	fi
	if [ "$F" = "B" ] || [ "$F" = "b" ]
		then
		d=$brat
		f=1
		if [ "$BREIT" = "1" ]
		then
		lavopt="-s 2 $filter -a 480x406+0+90"
		else
		lavopt="-s 2 $filter -a 480x540+0+18"
		fi
		mpegopt="-m 1 -b $brat $quopt $mpegfilter -r 16 "
		mplexopt="vcdmplex"
#
# Nein, nicht mplex - bei mir erzeugte mplex eine etwas zu hohe
# Bitrate - der Film ruckelt auf dem DVD-Spieler. Bei vcdmplex
# habe ich dieses Ph„nomen nicht.
#
# No, don't use mplex, unless you are really sure, that it works
# for you - my DVD-Player fails - bitrate might be slightly too high
#
		add="${brat}_xvcd"
		o="XVCD MPEG 1 mit $brat "
	fi
	if [ "$F" = "C" ] || [ "$F" = "c" ]
		then
		d=$brat
		f=1
	if [ $BREIT = "1" ]
	then
	lavopt="-s 1 $filter -a 352x202+0+43"
        else
	lavopt="-s 1 $filter -a 352x270+0+9"
	fi
		mpegopt="-m 1 -b $brat $quopt $mpegfilter -r 16 "
		mplexopt="vcdmplex"
#
#		mplexopt="mplex -f 1 -S 840"
#
# Nein, nicht mplex - bei mir erzeugte mplex eine etwas zu hohe
# Bitrate - der Film ruckelt auf dem DVD-Spieler. Bei vcdmplex
# habe ich dieses Ph„nomen nicht.
#
# No, don't use mplex, unless you are really sure, that it works
# for you - my DVD-Player fails - bitrate might be slightly too high
#
		add="${brat}_vcd"
		o="VCD MPEG 1 mit $brat "
	fi
fi  # Ende Abfrage ob es eine VCD-Aufnahme ist
# End of "Is it a VCD-record or do I need more Information"
if [ ${c} \> "Zz" ] # Dateiname mit Kleinbuchstabe First letter not a capital
	then
	echo -e "\n Bitte Ausgabe-Name angeben \c"
# English echo -e "\n Enter Output-Name \c"
	read aus
fi
echo -e "\nWartezeit in Minuten  (Enter startet sofort, CTRL-C unterbricht) \c"
# English echo -e "\n Enter delay in minutes (Just ENTER starts, CTRL-C to break \c"
read warte
if [ -z "$warte" ]
	then
	warte=0
	else
	warte=`expr $warte \* 60`
fi
sleep $warte
if [ ${c} \> "Zz" ] # Dateiname mit Kleinbuchstabe
	then
	auszahl="1"
	maches="ja"
	null=`expr $auszahl \< "10"`
	if [ -n $null ]
	then
	auszahl="0"$auszahl
	fi
	klein=${c}${auszahl}*
	machs=`ls $klein 2>/dev/null`
	if [ -n "$machs" ]
	then
    maches="ja"
	else
    echo "Keine Dateien zur Verarbeitung gefunden"
# English echo "No files found "
	maches="nein"
	fi
while [ "$maches" = "ja" ]
do
	echo ${aus}${auszahl}_${add}
	if [ -f ${aus}${auszahl}_${add} ] || [ -f ${aus}${auszahl}_${add}.mpg ]
	then
	echo "MPEG-File ${aus}${auszahl}_${add} exists"
	else
        if [ "$filter2" = "lav2dfilter" ]
	then
	lav2yuv $lavopt $klein | lav2dfilter | mpeg2enc $mpegopt -o ${aus}${auszahl}_${add}
	else
	lav2yuv $lavopt $klein | mpeg2enc $mpegopt -o ${aus}${auszahl}_${add}
	fi
	fi
    if [ -f ${aus}${auszahl}.snd ]
	then
	echo "Soundfile ${aus}${auszahl}.snd exists"
	else
	lav2wav $klein | mp2enc -v -o ${aus}${auszahl}.snd
	fi
	if [ -f ${aus}${auszahl}_${add}.mpg ]
	then
	echo "${aus}${auszahl}_${add}.mpg exists"
	else
	$mplexopt ${aus}${auszahl}_$add ${aus}${auszahl}.snd ${aus}${auszahl}_${add}.mpg
	fi
	auszahl=`expr $auszahl \+ 1`
#        echo $auszahl
	null=`expr $auszahl \< "10"`
	if [ $null = "1" ]
	then
	auszahl="0"$auszahl
	fi
	klein=${c}${auszahl}*
#        echo $klein
	machs=`ls $klein 2>/dev/null`
	if [ -n "$machs" ]
	then
    maches="ja"
	else
	maches="nein"
	fi
	done
else
for i in ${c}*avi
do
a=`basename $i .avi`
if [ -f ${a}_${add} ] || [ -f ${a}_${add}.mpg ]
then
echo "MPEG-File ${a}_${add} exists"
else
lav2yuv $lavopt $i  | mpeg2enc $mpegopt -o ${a}_${add}
fi
if [ -f ${a}.snd ]
then
echo "Soundfile exists"
else
lav2wav $i | mp2enc -v -o ${a}${auszahl}.snd
fi
if [ -f ${a}_${add}.mpg ]
then
echo "MPLEX-File ${a}_${d}_mp${f}.mpg exists"
else
$mplexopt ${a}_${add} ${a}.snd ${a}_${add}.mpg
if [ -f ${a}_${add}.mpg ]
then
rm ${a}_${add}
fi
fi
done
fi
