#!/usr/bin/python


import MySQLdb

guide = MySQLdb.Connect(db='tvguide');
cursor = guide.cursor();


stmt = "Drop Table if exists listings"
cursor.execute(stmt);

stmt = """CREATE TABLE listings (
	id int unsigned not null auto_increment,
	start_time DateTime not null,
	end_time DateTime not null,
	length smallint not null,
	station char(12) not null,
	title varchar(80) not null,
	primary key (id),
	key start_time (start_time),
	key end_time (end_time),
	key time_station (start_time, station)
)"""
cursor.execute(stmt)

stmt = "Drop Table if exists stations"
cursor.execute(stmt);

stmt = """CREATE TABLE stations (
	id int unsigned not null auto_increment,
	station char(12) not null,
	name char(12) not null ,
	description char(80),
	tuner char(16),
	channel char(4),
	primary key (id),
	key station (station),
	key name (name)
)"""
cursor.execute(stmt)

stmt = "Drop Table if exists events"
cursor.execute(stmt);


stmt = """CREATE TABLE events (
	id int unsigned not null auto_increment,
	channel_id int unsigned not null,
	listing_id int unsigned not null,
	start_time DateTime not null,
	end_time DateTime not null,
	length smallint not null,
	repeat char(16),
	description char(80),
	primary key (id),
	key start_time (start_time),
	key channel_id (channel_id)
)"""
cursor.execute(stmt)

		


