LIB_DIR = /usr/lib/site-python
BIN_DIR = /usr/local/bin
ETC_DIR = /etc

install:
	install -m 644 tvguide.py ${LIB_DIR}
	install -m 644 guide.py ${LIB_DIR}
	install -m 755 tvguide ${BIN_DIR}
	install -m 644 dvcr ${ETC_DIR}
