#define dv_videosegment_t_i                      0
#define dv_videosegment_t_k                      4
#define dv_videosegment_t_bs                     8
#define dv_videosegment_t_mb                     16
#define dv_videosegment_t_isPAL                  12656
#define dv_macroblock_t_size                     2528
#define dv_macroblock_t_b                        16
#define dv_macroblock_t_eob_count                2524
#define dv_macroblock_t_vlc_error                2520
#define dv_macroblock_t_qno                      2512
#define dv_macroblock_t_sta                      2516
#define dv_macroblock_t_i                        0
#define dv_macroblock_t_j                        4
#define dv_macroblock_t_k                        8
#define dv_block_t_size                          416
#define dv_block_t_coeffs                        0
#define dv_block_t_dct_mode                      384
#define dv_block_t_class_no                      388
#define dv_block_t_reorder                       392
#define dv_block_t_reorder_sentinel              396
#define dv_block_t_offset                        400
#define dv_block_t_end                           404
#define dv_block_t_eob                           408
#define dv_block_t_mark                          412
#define bitstream_t_buf                          12
