#!/bin/sh

# mjpegtools-config
#
# Tool for retrieving the library/include paths mjpegtools libs were
# compiled with.
#
# This work is released under the GNU GPL, version 2 or later.

prefix="/usr/local"
exec_prefix="${prefix}"
exec_prefix_set=no
data_dir="${prefix}/share/mjpegtools"

version="1.5.4"
include_dir="${prefix}/include/mjpegtools"
lib_dir="${exec_prefix}/lib"

usage()
{
    cat <<EOF
Usage: mjpegtools-config [OPTIONS]
Options:
    [--prefix[=DIR]]
    [--exec-prefix[=DIR]]
    [--version]
    [--libs]
    [--cflags]

EOF
    exit $1
}

if test $# -eq 0; then
    usage 1 1>&2
fi

while test $# -gt 0; do
    case "$1" in
	-*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
	*) optarg= ;;
    esac

    case $1 in
	--prefix=*)
	    prefix=$optarg
	    if test $exec_prefix_set = no ; then
		exec_prefix=$optarg
	    fi
	    ;;

	--prefix)
	    echo_prefix=yes
	    ;;

	--exec-prefix=*)
	    exec_prefix=$optarg
	    exec_prefix_set=yes
	    ;;

	--exec-prefix)
	    echo_exec_prefix=yes
	    ;;

	--version)
	    echo $version
	    ;;

	--cflags)
	    echo_cflags=yes
	    ;;

	--libs)
	    echo_libs=yes
	    ;;

	*)
	    usage 1 1>&2
	    ;;
    esac
  shift
done

if test "$echo_prefix" = "yes"; then
    echo $prefix
fi

if test "$echo_exec_prefix" = "yes"; then
    echo $exec_prefix
fi

cflags="-I$include_dir"

if test "$lib_dir" != "/usr/lib"; then
    libs="-L$lib_dir -lmjpegutils"
else
    libs="-lmjpegutils"
fi

if test "$echo_cflags" = "yes"; then
    echo $cflags
fi

if test "$echo_libs" = "yes"; then
    echo $libs
fi
