#!/usr/bin/python
#
#    Copyright (C) 2000 Mike Bernson <mike@mlb.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
import v4l, V4L

device = v4l.V4l()
name, type, channels, audios, max_width, max_height, min_width, min_height = device.query_capability()

print "name: %s" % name
print "capability: %s " % device.decode_cap_types(type)
print "video channels: %d" % channels
for channel in range(0, channels):
	chan, name, tuner, flags, type, norm = device.get_video_source(channel)
	print "\t" + device.decode_chan(name, tuner, flags, type, norm)
print "audio channels: %d" % audios
print "min grab: %d x %d" % (min_width, min_height)
print "max grab: %d x %d" % (max_width, max_height)

