.\" 
.TH "lav2yuv" "1" "2 June 2001" "MJPEG Linux Square" "MJPEG tools manual"
.SH "NAME"
lav2yuv \- Convert a MJPEG file to raw yuv

.SH "SYNOPSIS"
.B lav2yuv
.RI [ options ]
.I filename " ..."

.SH "DESCRIPTION"
\fBlav2yuv\fP converts an MJPEG video sequence described by a sequence
of MJPEG video files and/or edit lists pointing to such files into the
simple uncompressed planar YUV format. Used by \fBmpeg2enc\fP(1) 
MPEG encoder and image processing filters like
\fByuvscaler\fP(1) or \fByuv2dfilter\fP(1) or \fByuvdenoise\fP(1).

Output is to stdout so that by piping the output of lav2yuv into a
suitable pipeline it is possible to process and then encode or play
back video recorded in any of the mjpegtools MJPEG container formats:
AVI, quicktime or movtar or edit lists describing editted versions of
video held in such files.

For historical reasons lav2yuv has simple scaling and cropping facilities
built\-in although superior facilities are also available through the
\fByuvscaler\fP(1) filter.

Mixing differnt files with different video formats is currently not possible.

The \fB\-S \-T \-D\fP options are used for scene detection,
which is used by linux video studio.

.SH "OPTIONS"
\fBlav2yuv\fP accepts the following options:

.TP 5
.BI \-a " widthxhight+x+y"
Sets everything that is not in the described area to black
.TP 4
.BI \-s " num"
Special output format option:
 0 output like input, nothing special
 1 create half height/width output from input
 2 create 480 wide output from 720 wide input (SVCD)
 3 create 352 wide output from 720 wide input (VCD)
 4 create 480 x 480 output from 720 x 240 input (SVCD)
.TP 5
.BI \-d \ [0..3]
Drop lsbs of samples (default: 0) Improves the quality a bit, because the less sigificant bits of every sample are dropped. Reduces the number of different colors
.TP 5
.BI \-n \ [0..2]
Noise filter (low\-pass) (default: 0) This removes low fequency noise in the picture

.TP 5
.BI \-m 
Force mono\-chrome
.TP 5
.BI \-x 
Exchange fields for interlaced frames
.TP 5
.BI \-S " list.el"
Output a scene list with scene detection
.TP 5
.BI \-T " num"
Set scene detection threshold to num (default: 4)
.TP 5
.BI \-D " num"
Width decimation to use for scene detection (default: 2)
.TP 5
.BI \-o " num"
Frame offset skip num frames in the beginning if num is negative, 
all but the last num frames are skipped
.TP 5
.BI \-f " num"
Only num frames are written to stdout. 0 means that all frames aure procced. 
.TP 5
.BI \-I \ [0..3]
De-Interlacing mode for DV input 
.TP 5
.BI \-i \ [0..65025]
De-Interlacing spatial threshold (default: 440) for DV
.TP 5
.BI \-j \ [0..65025]
De-Interlacing temporal threshold (default: 220) for DV
.TP 5
.BI \-Y
switch field order in DV input

.SH "AUTHOR"
This man page was written by Bernhard Praschinger.
.br 
If you have questions, remarks, problems or you just want to contact
the developers, the main mailing list for the MJPEG\-tools is:
  \fImjpeg\-users@lists.sourceforge.net\fP

.TP 
For more info, see our website at
.I http://mjpeg.sourceforge.net

.SH "SEE ALSO"
.BR mjpegtools (1),
.BR mpeg2enc (1),
.BR yuvscaler (1),
.BR yuv2lav (1),
.BR yuvdenoise (1),
.BR yuvplay (1)
