.TH "lavrec" "1" "V 1.4" "Ronald Bultje" "description"
.SH NAME
lavrec \- Record MJPEG-video from a zoran-device
.SH SYNOPSIS
lavrec [options] [filename(s)]
.SH DESCRIPTION
\fBlavrec\fP can be used to record video in MJPEG format (either
quicktime, movtar or AVI) from a zoran video-capture device, such as
the Miro/Pinnacle DC10(+), the Iomega Buz or Linux Media Labs' LML33.
.SH OPTIONS
\fBlavrec\fP accepts the following options:
.TP 8
.B  \-f [aAqm]
The format in which the video should be saved to the harddisk.
  a - MJPEG AVI
  A - MJPEG AVI with fields exchanged
  q - Quicktime
  m - Movtar
.TP 8
.B  \-p [pPnNsStTa]
The recording source and the video source standard format.
  p - PAL through the Composite-in
  P - PAL through the S-Video
  n - NTSC through the Composite-in
  N - NTSC through the S-Video
  s - SECAM through the Composite-in
  S - SECAM through the S-Video
  t - PAL through the TV-tuner input
  T - NTSC through the TV-tuner input
  a - Auto-detect (default)
.TP 8
.B  \-d num
Recording decimation, either 1, 2 or 4. This will decimate the size
of the recorded video horizontally and vertically. To use different
horizontal and vertical decimations, use two numbers, the first one
being the horizontal and the second one being the vertical (-d 12).
.TP 8
.B  \-g WxH+X+Y
An X-style geometry string, giving the geometry of the full-sized
frame to record. The default is the full frame, so 720x576/480 for
Buz/LML33-users and 640x480 or 768x576 for DC10(+)-users.
.TP 8
.B  \-q num
Quality of the video to be recorded (in percent). This must be a
number between 0 and 100. Lower quality should generally mean lower
filesize, higher quality will take more diskspace but will give more
detailed perfectness in the resulting recorded video.
.TP 8
.B  \-t num
Recording time in seconds. The default is unlimited. To stop capturing
video while recording, use Ctrl-C.
.TP 8
.B  \-S
Single-frame capture mode. This means that one can capture individual
frames from the capture device.
.TP 8
.B  \-T num
time-lapse factor, which means that only every <num>th frame is saved
to the recording file.
.TP 8
.B  \-w
If this option is given, lavrec will wait for the user to press enter
before starting to record.
.TP 8
.B  \-a num
Audio size in bits, either 0, 8 or 16. 0 means no audio.
.TP 8
.B  \-r num
Audio sampling rate in Hz. This must be a sampling rate which is
supported by the soundcard. Often-supported audio sampling rate values
are 11025, 22050 or 44100.
.TP 8
.B  \-s
Capture in stereo. By default, lavrec captures in mono.
.TP 8
.B  \-l num
Recording level. This must be a value between 0 (no sound) and 100
(loud recording). -1 means to not touch the mixer settings at all.
.TP 8
.B  \-m
Mute sound output while recording. This can be useful when recording
sound from the microphone to disable echos.
.TP 8
.B  \-R [lmc]
Recording source, either (l)ine-in, (m)icrophone or (c)d-rom.
.TP 8
.B  \-c [012]
Audio/video synchronization level efforts. (0) means no synchronization,
(1) means that lavrec will replicate frames for lost frames. (2) means
that lavrec will replicate frames for lost frames and do sync correction.
.TP 8
.B  \-n num
Number of MJPEG-buffers. Default is 32. Try changing this number if you
have many lost frames.
.TP 8
.B  \-b num
MJPEG buffersize in kilobytes. The default is 256 kb.
.TP 8
.B \-v num
Verbosity level (0, 1 or 2)
.SH ENVIRONMENT VARIABLES
The following environment variables can be recognized by lavrec:
.TP 8
.B LAV_VIDEO_DEV
The video device. Default is /dev/video
.TP 8
.B LAV_AUDIO_DEV
The audio device. Default is /dev/dsp
.TP 8
.B LAV_MIXER_DEV
The mixer device. Default is /dev/mixer
.SH SEE ALSO
.BR mjpeg (1),
.BR lavplay (1)
.SH CONTACTING
If you have questions, remarks, problems or you just want to contact
the developers, the main mailing list for the MJPEG\-tools is:
  \fImjpeg\-users@lists.sourceforge.net\fP

For more info, see our website at \fIhttp://mjpeg.sourceforge.net/
