.TH "mplex" "1" "2 June 2001" "MJPEG Linux Square" "MJPEG tools manual"

.SH "NAME"
.LP 
.br 
mplex \- MPEG 1/2 program/system stream multiplexer
.br 
.SH "SYNOPSIS"
.B mplex
.RB [ -v
.IR num ]
.RB [ -m\ 1 | 2 ]
.RB [ -b
.IR video_buffer_size_kB ]
.RB [ -r
.IR muxed_bitrate_kbps ]
.RB [ -l
.IR num ]
.RB [ -O
.IR num ]
.RB [ -f
.IR format_code ]
.RB [ -V ]
.RB [ -s
.IR sector_size_B ]
.RB [ -p
.IR num ]
.RB [ -S
.IR output_filesize_limit_MB ]
.RB [ -M ]
.RB [ -h ]
.RB [ -? ]
.BI -o \ output_filename_pattern
.SH "DESCRIPTION"
Mplex is a simple two-stream audio/video multiplexer for
MPEG-1/MPEG-2.  It accepts an MPEG-1/2 video stream and/or an MPEG
layer II/III audio stream and multiplexes them into a combined
program/system stream according to the constraints specified.  Many
different types of output structure are supported along with presets
for standard VCD and SVCD streams.  These latter can be burned to CD using
tools such as \fBvcdimager\fP(1) and played in stand-alone players.

It is also capable of automatically splitting the output stream into
chunks of a specified size either independently or a sequence end/start
points in the input video stream.
.SH "GENERAL FUNCTION LETTERS"
.TP
.BI -o \ output_filename_pattern
This (compulsorary) option sets the pattern for the name(s) of output files.

An integer format code (e.g. %d) in the name is replaced by the number of
the file generated (see \fBprintf\fP(3)).
.TP
.BI -v \ num
Set verbosity level to \fInum\fP:
 0 - warnings and errors only,
 1 - information as well,
 2 - really verbose.
.TP
.B -?
Display a synopsis of the command syntax.
.br
.SH "FUNCTION LETTERS CONTROLLING OUTPUT STREAM STRUCTURE"
.TP
.BI -f \ format_code
This command allows one of a number of convenient preset output
formats to be selected without the need to individually set numerous
parameters.  In particular producing VCD or SVCD compliant output requires
the use of the appropriate presets as these require a number of (rather odd)
VCD-specific constraints to be activated.
.IP
 0 - Auto MPEG1.  A simple general-purpose MPEG1 format primarily suitable
for software decoders.  Buffer sizes and VBR must be specified.
Bit-rate can be auto-detected.
 1 - VCD.  Standard VCD.  Overrides other option settings.
 2 - User VCD.  VCD format but buffer size, bit rate and VBR can be set
manually.
 3 - Auto MPEG2.  Like 0 expect MPEG2.
 4 - SVCD.  Standard SVCD.  Overrides other option settings.
 5 - User-rate SVCD.  SVCD format but buffer size and bit rate  can be set.
.TP
.BR -m\ 1 | 2
Set MPEG-1 or MPEG-2 multiplexing.
.TP
.BI -r \ num
The total (non VBR) / peak (VBR) bit-rate of the output stream in k
Bits/sec. If unspecified and not set by a preset it is automatically
calculated from the input stream.
.TP
.BI -b \ num
The size of the video input buffer available in the target decoder.
The default is 46KB the (tiny) size specified for VCD.  The
size to use for SVCD is the (more reasonable) 230KB.  If you are
encoding for a half-decent software decoder it makes sense to push
this up to 500K or more.
.TP
.BI -l \ num
Multiplex limit.  Multiplex only the specified number of sectors.  Useful
for tuning and debugging.
.TP
.BI -O \ num
Set the presentation timestamp offset of video stream w.r.t. audio stream (video-audio) in mSec.   This flag is used to produce a stream with synchronised
audio/video when one stream started before/after the other.  This is common
when transcoding as the synchronisation information is typically lost during
the (seperate) decoding/encoding of audio and video.
.TP
.B -V
Set variable bit rate multiplexing.  This is needed to multiplex variable
bit-rate video streams correctly.
.TP
.BI -s \ num
This option specifies the sector size of the output stream in bytes.
.TP
.BI -p \ num
This option specifies the number of packets per pack in the output stream.
.TP
.BI -S \ num
This option specifies the maximum size of output files in MBytes (2^10).
The default is 2000 Mbytes (splitting output before 2G limits can hit).
When the limit is reached a  new file is started.
.IP
Note: This option is 
.I not
suitable for splitting a long video across multiple VCD's or SVCD's.
It simply splits a single long sequenctreame into chunks.  To replay the
sequence the chunks have to be concatenated.  For VCD / SVCD a different
technique is used.  If mplex encounters a sequence break (sequence end followed
by start) in the input video stream it starts a new output stream and file
at the sequence start.  Thus to split a long video across VCD's/SVCD's you
have to get the MPEG video encoder to introduce sequence splits at the
right points (see mpeg2enc(1) for details of how to do this).
.TP
.B -M
When splitting a long stream in files based on -S mplex does a certain
amount of sanity checking.  If the files are going to be concatenated
for playback this checking is superfluous.  -M suppresses this checking.
.TP
.B -h
A system header is generated in every pack rather than just in the first.
.SH "DIAGNOSTIC OUTPUT"
When multiplexing using mplex you may get warning or error messages
complaining about buffer underflow.  This means that the bit-rate you
have specified is simply too low to permit the video and audio to be
played back without skipping.  The fix is to either reduce the
data-rate of the input material or increased the output stream bit-rate.
.SH "BUGS"
Variable bit-rate should be auto-detected and supported for audio
as well as video.

The ludicrous two-pass parsing structure should be made single pass.

The multiplexer should handle AC3 and MPEG(5.1) audio too.
.SH AUTHOR
This man page was written by Andrew Stevens.
.br
If you have questions, remarks, problems or you just want to contact
the developers, the main mailing list for the MJPEG\-tools is:
  \fImjpeg\-users@lists.sourceforge.net\fP

For more info, see our website at
  \fIhttp://mjpeg.sourceforge.net\fP

.SH "SEE ALSO"
.BR mpeg2enc "(1), " mp2enc "(1), " lavrec "(1), " lavplay "(1), "
.BR lav2yuv "(1), " lav2wav "(1), " yuvscaler "(1)"
