.TH "studio-TV" "1" "V 0.1.5-dev" "Ronald Bultje" "description"
.SH NAME
Linux Video Studio TV - a TV application
.SH SYNOPSIS
stv [\-h] [\-v] [\-p num] [\-t] [\-d] [\-c name] [\-g WxH+X+Y] [\l device] [\m device]
.SH DESCRIPTION
\fBLinux Video Studio TV\fP is a simple TV-app for linux, based
on Gtk+. It works, that's all. It has no fancy special features,
like video capturing, image grabbing, bladiebla. Nothing of this
all. It just shows TV. Because that's all it needs to do.

.SH OPTIONS
\fBLinux Video Studio TV\fP ('stv') accepts the following options:
.TP 8
.B  \-h
Prints a help/usage message and quits
.TP 8
.B \-v
Prints version information and quits
.TP 8
.B \-p num
Gives you the possibility to select a Video4Linux Xvideo port to be used.
By default (if you omit this option or if you give 0 as an argument),
Linux Video Studio will try to select one automatically. You can select
another one with this option or in the Options window.
.TP 8
.B \-l device
The Linux Infrared Remote Control device file (default: /dev/lircd)
.TP 8
.B \-m device
The audio device to use for volume control
.TP 8
.B \-t
Prints Video4Linux Xvideo ports information and quits.
.TP 8
.B \-g WxH+X+Y
The preferred size of the video window (width x height), with the offset
in pixels (X and Y) which define the top left position of where to place
the window.
.TP 8
.B \-d
Enables verbose/debugging mode.
.TP 8
.B \-c name
The name (default: 'studio') is used to safe the configuration. By using
multiple names, you can use multiple configurations all for one user. For
example, if you have both a Buz and a DC10+, you could use '\-c buz' for
the Buz and '\-c dc10' for the DC10+ card so that the two configurations
will both be saved separately.
.SH SEE ALSO
.BR studio (1)

.SH BUGS
Do we contain bugs? Yes, very likely. We just don't know which bugs
yet, so that's for the user (you) to find out! If you've found bugs,
please mail a bug report to the developers (see \fBCONTACTING\fP).
Before sending bug reports saying nothing more than "it won't work",
please try running in a terminal window with the -d (debug) option
and attach the output to the bug report. Also, if it gives a segfault, 
please run the core-file through gdb or run studio within gdb and attach 
the output of gdb too, so that we know where it crashed.

.SH CONTACTING
This application was created by:
        Ronald Bultje <\fIrbultje@ronald.bitfreak.net\fP>

For bug reports, please make sure you're using the newest version. The 
newest version can always be downloaded from \fIhttp://ronald.bitfreak.net/\fP
