void denoise_frame(void);
void black_border (void);
void contrast_frame (void);
int  low_contrast_block (int x, int y);
void move_block (int x, int y);
void average_frame (void);
void difference_frame (void);
void correct_frame2 (void);
void denoise_frame_pass2 (void);
void sharpen_frame(void);
